apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ewltb7xwf-go
  janus-idp.io/tekton: ewltb7xwf-go
  backstage.io/kubernetes-id: ewltb7xwf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ewltb7xwf-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
